/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, Inquiry } from './types';

// Let's resolve the actual image URLs we generated.
const images = {
  hero: '/src/assets/images/hero_chemical_tank_1781660858614.jpg',
  ug: '/src/assets/images/ug_standard_tank_1781660874171.jpg',
  ud: '/src/assets/images/ud_drainage_tank_1781660890538.jpg',
  un: '/src/assets/images/un_agitation_tank_1781660904203.jpg',
  small: '/src/assets/images/small_pe_tank_1781660919123.jpg',
};

export const PRODUCT_DATA: Product[] = [
  {
    id: 'ug-3000',
    name: 'PE 케미칼탱크 UG 일반형 3톤',
    category: 'UG_STANDARD',
    categoryName: '케미칼저장탱크(UG/일반형)',
    image: images.ug,
    capacity: '3,000 리터 (3톤)',
    dimensions: 'Ø 1,600 x H 1,800 mm',
    features: [
      '고밀도 폴리에틸렌(HDPE) 일체성형 공법',
      '충격 및 내부식성이 매우 뛰어난 케미칼 전문 탱크',
      '오렌지색 이중 PE 보강강화 밴드링 기본 적용',
      '산, 알칼리 등 다양한 화학 약품 장기 안심 저장 가능',
    ],
    specs: {
      model: 'UW-UG-3000',
      capacity: '3,000 L',
      diameter: '1,600 mm',
      height: '1,800 mm',
      manhole: 'Ø 450 mm',
      thickness: '10 mm',
    },
    isNew: true,
  },
  {
    id: 'ud-5000',
    name: 'PE 케미칼탱크 완전배출형 UD 5톤',
    category: 'UD_DISCHARGE',
    categoryName: '완전배출형(UD)',
    image: images.ud,
    capacity: '5,000 리터 (5톤)',
    dimensions: 'Ø 1,900 x H 2,300 mm',
    features: [
      '탱크 바닥면 원추형(Cone Bottom) 설계로 잔량 100% 완전 배출',
      '하단 배관 플랜지 조립형으로 간편한 유지 보수',
      '안정적인 하부 아웃라인 전용 세이프티 스탠드 프레임 장착',
      '약품 잔류로 인한 오염이나 침전물 세척에 탁월함',
    ],
    specs: {
      model: 'UW-UD-5000',
      capacity: '5,000 L',
      diameter: '1,900 mm',
      height: '2,300 mm',
      manhole: 'Ø 500 mm',
      thickness: '12 mm',
    },
    isNew: true,
  },
  {
    id: 'un-2000',
    name: 'PE UN형 케미칼교반형탱크 2톤',
    category: 'UN_AGITATION',
    categoryName: '교반형/소형탱크',
    image: images.un,
    capacity: '2,000 리터 (2톤)',
    dimensions: 'Ø 1,400 x H 1,650 mm',
    features: [
      '상부 구동부 감속 기어모터 및 안전 프레임 장착 설계',
      'STS304/STS316L 테플론 코팅 교반 샤프트 및 패들 적용',
      '정밀한 약품 혼합 및 교반 반응 공정에 표준 채택',
      '수위계, 스케일 게이지 및 센서 취부 옵션 선택 가능',
    ],
    specs: {
      model: 'UW-UN-2000',
      capacity: '2,000 L',
      diameter: '1,400 mm',
      height: '1,650 mm',
      manhole: 'Ø 450 mm',
      thickness: '10 mm',
    },
    isNew: true,
  },
  {
    id: 'deck-10000',
    name: 'PE 케미칼탱크 DECK형 10톤',
    category: 'DECK_STS',
    categoryName: 'DECK형/STS밴드형',
    image: images.ug,
    capacity: '10,000 리터 (10톤)',
    dimensions: 'Ø 2,400 x H 2,700 mm',
    features: [
      '상부 고하중 안전 점검용 우철 데크(DECK) 프레임 적용형',
      '외부 점검용 STS304 사다리 및 안전 난간 일체형 설계',
      '대용량 저장 시 내외압 분산 구조로 완벽한 장기 복원력',
      '울트라월드만의 고품격 B2B 특수 주문 제작 시그니처 사양',
    ],
    specs: {
      model: 'UW-DK-10000',
      capacity: '10,000 L',
      diameter: '2,400 mm',
      height: '2,700 mm',
      manhole: 'Ø 600 mm',
      thickness: '15 mm',
    },
    isNew: true,
  },
  {
    id: 'un-1000',
    name: 'PE UN형 케미칼 교반용탱크 1톤',
    category: 'UN_AGITATION',
    categoryName: '교반형/소형탱크',
    image: images.un,
    capacity: '1,000 리터 (1톤)',
    dimensions: 'Ø 1,100 x H 1,300 mm',
    features: [
      '소규모 실험실, 수처리 공정 맞춤형 정밀 회전 속도 교반 조절',
      '컴팩트한 상부 보강 지지판과 경량 모터 마운트',
      '투명 수위 게이지 장착 및 약품 계량 스케일 성형 표시',
    ],
    specs: {
      model: 'UW-UN-1000',
      capacity: '1,000 L',
      diameter: '1,100 mm',
      height: '1,300 mm',
      manhole: 'Ø 450 mm',
      thickness: '8 mm',
    },
    isNew: true,
  },
  {
    id: 'ug-10000',
    name: 'PE 케미칼탱크 UG 일반형 10톤',
    category: 'UG_STANDARD',
    categoryName: '케미칼저장탱크(UG/일반형)',
    image: images.ug,
    capacity: '10,000 리터 (10톤)',
    dimensions: 'Ø 2,400 x H 2,700 mm',
    features: [
      '대용량 염수, 수처리 설비, 도금액 다목적 화학 저장소',
      '고밀도 강화 원단 두께 설계로 장기 고온 저항성 확보',
      '안전 수위 측정용 디스플레이 및 플랜지 노즐 맞춤 타공',
    ],
    specs: {
      model: 'UW-UG-10000',
      capacity: '10,000 L',
      diameter: '2,400 mm',
      height: '2,700 mm',
      manhole: 'Ø 500 mm',
      thickness: '14 mm',
    },
    isNew: true,
  },
  {
    id: 'kd-small',
    name: 'PE 케미칼 소형탱크 KID형 500L',
    category: 'UN_AGITATION',
    categoryName: '교반형/소형탱크',
    image: images.small,
    capacity: '500 리터',
    dimensions: 'W 1,000 x D 700 x H 850 mm',
    features: [
      '사각형 콤팩트 도징(Dosing) 및 중화용 정량 펌프 장착 최적화',
      '가볍고 견고한 하우징으로 이동형 카트 취부 가능',
      '실험실, 연구실, 빌딩 공조 지하실 협소한 통로 간편 반입',
    ],
    specs: {
      model: 'UW-KD-500',
      capacity: '500 L',
      diameter: '폭 1,000 mm',
      height: '850 mm',
      manhole: 'Ø 350 mm',
      thickness: '6 mm',
    },
    isNew: true,
  },
  {
    id: 'sts-band-20000',
    name: 'PE 케미칼탱크 STS 밴드형 20톤',
    category: 'DECK_STS',
    categoryName: 'DECK형/STS밴드형',
    image: images.ug,
    capacity: '20,000 리터 (20톤)',
    dimensions: 'Ø 3,000 x H 3,100 mm',
    features: [
      '스테인리스 고장력 외부 밴드를 등간격 다중 체결하여 수압 극대 배분',
      '자외선 안정제를 특수 혼합하여 야외 장기 장착에도 고점도 연성 유지',
      '전국 최신 화학 공장 및 하수 유역 표준 공급 명품 모델',
    ],
    specs: {
      model: 'UW-STS-20000',
      capacity: '20,000 L',
      diameter: '3,000 mm',
      height: '3,100 mm',
      manhole: 'Ø 600 mm',
      thickness: '18 mm',
    },
    isNew: true,
  },
];

export const STATIC_SPEC_TABLE = [
  { model: 'UW-UG-1000', capacity: '1,000L', diameter: '1,100 mm', height: '1,250 mm', thickness: '8 mm', bandCount: '2 circles' },
  { model: 'UW-UG-2000', capacity: '2,000L', diameter: '1,400 mm', height: '1,500 mm', thickness: '9 mm', bandCount: '3 circles' },
  { model: 'UW-UG-3000', capacity: '3,000L', diameter: '1,600 mm', height: '1,800 mm', thickness: '10 mm', bandCount: '3 circles' },
  { model: 'UW-UG-5000', capacity: '5,000L', diameter: '1,900 mm', height: '2,100 mm', thickness: '11 mm', bandCount: '4 circles' },
  { model: 'UW-UG-10000', capacity: '10,000L', diameter: '2,400 mm', height: '2,700 mm', thickness: '14 mm', bandCount: '5 circles' },
  { model: 'UW-UG-15000', capacity: '15,000L', diameter: '2,600 mm', height: '3,000 mm', thickness: '16 mm', bandCount: '6 circles' },
  { model: 'UW-UG-20000', capacity: '20,000L', diameter: '3,000 mm', height: '3,100 mm', thickness: '18 mm', bandCount: '7 circles' },
  { model: 'UW-UG-30000', capacity: '30,000L', diameter: '3,400 mm', height: '3,600 mm', thickness: '22 mm', bandCount: 'Heavy Frame' },
  { model: 'UW-UG-50000', capacity: '50,000L', diameter: '4,000 mm', height: '4,200 mm', thickness: '26 mm', bandCount: 'Extreme Frame' },
];

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'inq-101',
    companyName: '(주)한일화학개발',
    picName: '정우성 부장',
    phone: '010-4492-3882',
    email: 'wsjung@hanilchem.co.kr',
    productType: '케미칼저장탱크 (UG 일반형)',
    capacityNeeded: '10,000 리터 (10톤) 2기',
    content: '신설 공장 염산 저장조 설계용으로 외장 보강 밴드가 강화된 사양의 규격과 도면, 그리고 견적 공문을 요청합니다.',
    hasDrawings: false,
    submittedAt: '2026-06-15 14:32',
    status: '검토중',
  },
  {
    id: 'inq-102',
    companyName: '태평양테크',
    picName: '이지은 과장',
    phone: '010-8273-1996',
    email: 'jieun@taepyoungtech.com',
    productType: '완전배출형 (UD)',
    capacityNeeded: '5,000 리터 (5톤) 1기',
    content: '중화제 투입용 완전배출형 탱크 견적 및 매설 안전 프레임 상세 규격 요청드립니다. 설계 캐드 도면이 있으시면 메일로 전송 부탁드립니다.',
    hasDrawings: true,
    drawingFileName: 'discharge_support_spec.dwg',
    submittedAt: '2026-06-16 09:15',
    status: '접수대기',
  },
];
